version: "2"

linters:
  enable:
    - bodyclose
    - goprintffuncname
    - misspell
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tparallel
    - whitespace
  disable:
    - errcheck
    - ineffassign
    - unused

linters-settings:
  exclude-generated: lax
  exclude-presets:
    - common-false-positives
  exclude-rules:
    # Exclude QA tests from some linters
    - path: ^qa/
      linters:
        - bodyclose
        - rowserrcheck
        - sqlclosecheck
        - staticcheck
    # Exclude test files
    - path: _test\.go$
      linters:
        - goprintffuncname
        - noctx

formatters:
  enable:
    - gofumpt
    - goimports