version: "2"

linters:
  enable:
    - bodyclose
    - goprintffuncname
    - misspell
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - whitespace
  disable:
    - errcheck
    - ineffassign
    - unused
    - staticcheck

linters-settings:
  exclude-generated: lax
  exclude-presets:
    - common-false-positives
  exclude-rules:
    # Exclude QA tests from some linters
    - path: ^qa/
      linters:
        - bodyclose
        - rowserrcheck
        - sqlclosecheck
    # Exclude test files
    - path: _test\.go$
      linters:
        - goprintffuncname
        - noctx
    # Exclude problematic packages with import issues
    - path: ^internal/agent/tools/mcp/
      linters:
        - bodyclose
        - rowserrcheck
        - sqlclosecheck
    - path: ^internal/tui/components/anim/
      linters:
        - bodyclose
    - path: ^internal/history/
      linters:
        - bodyclose
        - rowserrcheck
        - sqlclosecheck
    - path: ^internal/message/
      linters:
        - bodyclose
        - rowserrcheck
        - sqlclosecheck

formatters:
  enable:
    - gofumpt
    - goimports