package cmd

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestLogsCmd(t *testing.T) {
	t.Run("Command has correct metadata", func(t *testing.T) {
		assert.Equal(t, "logs", logsCmd.Use)
		assert.Equal(t, "View nexora logs", logsCmd.Short)
		assert.Contains(t, logsCmd.Long, "logs generated by Nexora")
	})

	t.Run("Has follow flag", func(t *testing.T) {
		flag := logsCmd.Flags().Lookup("follow")
		assert.NotNil(t, flag)
		assert.Equal(t, "f", flag.Shorthand)
		assert.Equal(t, "false", flag.DefValue)
		assert.Equal(t, "Follow log output", flag.Usage)
	})

	t.Run("Has tail flag with default value", func(t *testing.T) {
		flag := logsCmd.Flags().Lookup("tail")
		assert.NotNil(t, flag)
		assert.Equal(t, "t", flag.Shorthand)
		assert.Equal(t, "1000", flag.DefValue)
		assert.Contains(t, flag.Usage, "last N lines")
	})
}

func TestPrintLogLine(t *testing.T) {
	tests := []struct {
		name      string
		input     string
		shouldErr bool
	}{
		{
			name:      "Valid JSON log",
			input:     `{"msg":"test message","level":"info","time":"2024-01-01T00:00:00Z"}`,
			shouldErr: false,
		},
		{
			name:      "Invalid JSON",
			input:     `not json`,
			shouldErr: true,
		},
		{
			name:      "Empty string",
			input:     ``,
			shouldErr: true,
		},
		{
			name:      "Log with source",
			input:     `{"msg":"test","level":"debug","time":"2024-01-01T00:00:00Z","source":{"file":"test.go","line":42}}`,
			shouldErr: false,
		},
		{
			name:      "Log with extra fields",
			input:     `{"msg":"test","level":"error","time":"2024-01-01T00:00:00Z","error":"something went wrong","user":"test"}`,
			shouldErr: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// printLogLine doesn't return an error, it just handles invalid input gracefully
			// We're testing that it doesn't panic
			assert.NotPanics(t, func() {
				printLogLine(tt.input)
			})
		})
	}
}
